# Generated by Django 5.2.7 on 2025-10-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='file',
            new_name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
